### ISSUE TITLE
run-genny install 404 error

### ISSUE THREAD

**Issue by JulianZackWu** [mongodb/genny#962]
root@706463ebd42e:~/project/genny# ./run-genny install
Downloading https://s3.amazonaws.com/boxes.10gen.com/build/curator/curator-dist-not-linux-3df28d2514d4c4de7c903d027e43f3ee48bf8ec1.tar.gz to /root/project/genny/build/curator.tgz
Traceback (most recent call last):
  File "/root/project/genny/src/lamplib/src/genny/cli.py", line 578, in <module>
    cli()
  File "/root/project/genny/genny_venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/project/genny/genny_venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/project/genny/genny_venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/project/genny/genny_venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/project/genny/genny_venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/project/genny/genny_venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/project/genny/src/lamplib/src/genny/cli.py", line 118, in cmake_compile_install
    curator.ensure_curator_installed(
  File "/root/project/genny/src/lamplib/src/genny/curator.py", line 197, in ensure_curator_installed
    downloader.fetch_and_install()
  File "/root/project/genny/src/lamplib/src/genny/download.py", line 76, in fetch_and_install
    self._fetch_and_install_impl()
  File "/root/project/genny/src/lamplib/src/genny/download.py", line 113, in _fetch_and_install_impl
    urllib.request.urlretrieve(url, tarball, ProgressBar())
  File "/usr/lib/python3.11/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by abondarev84** [comment]
@JulianZackWu any update on this? 
any fixes? simply going to a newer hash solved the issue for you?
